<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <Platforms>x64;ARM64</Platforms>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Recommended</AnalysisMode>
    <NuGetAuditMode>direct</NuGetAuditMode>
    <PlatformTarget>$(Platform)</PlatformTarget>
  </PropertyGroup>
</Project>
